### ISSUE TITLE
htmlファイルの設定

### ISSUE THREAD

**Issue by Shigurex** [kyamagis/http_socket#62]
http://localhost:8085/delete/${path} の部分で8085と決め打ちすると、8080番のポートの際にリスポンスが返されないエラーを起こす。

<img width="722" alt="スクリーンショット 2023-06-08 13 58 34" src="https://github.com/kyamagis/http_socket/assets/90454555/cb0844a9-3995-4ade-8db4-076634ed874b">

**Comment by Tommyscoffee** [comment]
ポート番号を入力してもらう方にします
